BOARD_TAG    = mega2560
ARDUINO_PORT = /dev/tty.usbmodem*
ARDUINO_LIBS = Ethernet Ethernet/utility spi arduinounit/src arduinounit/src/utility aJson aJson/utility LemmaLib LemmaLibTests/mocks
USER_LIB_PATH = ..

include ../Arduino-Makefile/arduino-mk/Arduino.mk
